server:
  port: 8383

xyz:
  baseTileDirectory: "/tmp/tiles"
  maxTileStorage: 1000000000
  layers:
    - name: "satellite"
      urlTemplate: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    - name: "osm"
      urlTemplate: "https://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
#  boundingBoxes:
#    - preCache: true
#      maxZoom: 5
#      north: 70
#      south: -70
#      east: 179
#      west: -179
